# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

APPLY_FIXES: all

# ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
ENABLE_LINTERS:
  - MARKDOWN_MARKDOWNLINT
  - TERRAFORM_TFLINT
  - TERRAFORM_TERRAFORM_FMT

PRINT_ALL_FILES: false

GITHUB_STATUS_REPORTER: true

FILTER_REGEX_EXCLUDE: >
  (\.automation/test|\.automation/generated|\.venv|\.github/workflows|
  docs/javascripts|docs/overrides|docs/json-schemas|flavors|clj-kondo|TEMPLATES)

BASH_FILTER_REGEX_EXCLUDE: "(lib)"

MARKDOWN_FILTER_REGEX_EXCLUDE: '(license\.md|docs/licenses)'
MARKDOWN_MARKDOWN_LINK_CHECK_DISABLE_ERRORS: true
MARKDOWN_SUMMARY_REPORTER: true

SHOW_ELAPSED_TIME: true

FLAVOR_SUGGESTIONS: false

EMAIL_REPORTER: false

FILEIO_REPORTER: false

JSON_REPORTER: true
